-- Rename ProductType enum values
-- ROPA -> MERCH
-- PARAFERNALIA -> SELECTED_GEAR

ALTER TYPE "ProductType" RENAME VALUE 'ROPA' TO 'MERCH';
ALTER TYPE "ProductType" RENAME VALUE 'PARAFERNALIA' TO 'SELECTED_GEAR';
